# Generated by Django 4.0.4 on 2022-05-12 13:32

from django.db import migrations


def default_user_admin(apps, schema_editor):
    User = apps.get_model("accounts", "Accounts")
    User.objects.create_superuser(username="admin", password="1234")


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_alter_accounts_user_uuid"),
    ]

    operations = [migrations.RunPython(default_user_admin)]
