# Generated by Django 4.0.4 on 2022-05-18 13:35

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bands', '0001_initial'),
        ('genres', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Musics',
            fields=[
                ('music_uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('band', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='musics', to='bands.bands')),
                ('genres', models.ManyToManyField(related_name='musics', to='genres.genres')),
            ],
        ),
    ]
