# Generated by Django 4.0.4 on 2022-05-16 13:40

from os import getenv

from django.db import migrations
from django.db.migrations.state import StateApps
from dotenv import load_dotenv

from users.models import Users

# from django.db.backends.sqlite3.schema import DatabaseSchemaEditor -> sqlite3



load_dotenv()


def default_user_admin(apps: StateApps, _):
    User: Users = apps.get_model("users", "Users")
    User.objects.create_superuser(
        username=getenv("ADMIN_USERNAME"),
        password=getenv("ADMIN_PASSWORD"),
    )


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [migrations.RunPython(default_user_admin)]
