# Generated by Django 4.0.4 on 2022-05-06 13:11

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoices',
            name='invoice_number',
            field=models.CharField(default=uuid.uuid4, max_length=65, unique=True),
        ),
        migrations.AlterField(
            model_name='invoices',
            name='release_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
